language: csharp
script:
  - xbuild /p:Configuration=Debug PolBasis.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore PolBasis.sln
after_script:
  - nunit-console PolBasis/bin/Debug/PolBasis.exe
